name: Continuous Integration with DOM/Javac
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}-dom
    cancel-in-progress: true

on:
  push:
    branches: [ 'dom-with-javac' ]
  pull_request:
    branches: [ 'dom-with-javac' ]

jobs:
  build-dom-javac:
    runs-on: ubuntu-latest
    steps:
    - name: Install xmllint
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libxml2-utils
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up JDKs â˜•
      uses: actions/setup-java@v4
      with:
        java-version: |
          8
          17
          21
          23
          24
        mvn-toolchain-id: |
          JavaSE-1.8
          JavaSE-17
          JavaSE-21
          JavaSE-23
          JavaSE-24
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.9
    - name: Build with Maven ðŸ—ï¸
      run: |
        mvn install --batch-mode -DskipTests -Pbree-libs -Dtycho.buildqualifier.format="'z'yyyyMMdd-HHmm" -Dproject.build.sourceEncoding=UTF-8 -pl org.eclipse.jdt.core.javac,org.eclipse.jdt.core.javac.feature,org.eclipse.jdt.core.tests.model,org.eclipse.jdt.core.tests.compiler
        mvn verify --batch-mode -f org.eclipse.jdt.core.tests.javac --fail-at-end -Ptest-on-javase-24 -Pbree-libs -DfailIfNoTests=false -DexcludedGroups=org.junit.Ignore -DproviderHint=junit47 -Papi-check -Dproject.build.sourceEncoding=UTF-8 -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true
    - name: 'Upload Artifact'
      if: success() || failure()    # run this step even if previous step failed
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: '*/target/surefire-reports/TEST-*.xml' 
    - name: Test Report
      if: success() || failure()    # run this step even if previous step failed
      run: |
        message="â–¶ï¸ TESTS RUN: $(xmllint --xpath 'string(/testsuite/@tests)' */target/surefire-reports/TEST-*.xml | awk '{n += $1}; END{print n}' -)
        âŒ FAILURES: $(xmllint --xpath 'string(/testsuite/@failures)' */target/surefire-reports/TEST-*.xml | awk '{n += $1}; END{print n}' -)
        ðŸ’¥ ERRORS: $(xmllint --xpath 'string(/testsuite/@errors)' */target/surefire-reports/TEST-*.xml | awk '{n += $1}; END{print n}' -)
        ðŸ›‘ SKIPPED: $(xmllint --xpath 'string(/testsuite/@skipped)' */target/surefire-reports/TEST-*.xml | awk '{n += $1}; END{print n}' -)"
        echo "$message"
        echo "$message" >> $GITHUB_STEP_SUMMARY
